data_vocabs = {
    'ace05-r': {"entity_type": {"ORG": 1, "VEH": 2, "FAC": 3, "WEA": 4, "LOC": 5, "GPE": 6, "PER": 7, "O": 0},
                "event_type": {"O": 0},
                "relation_type": {"PER-SOC": 1, "PART-WHOLE": 2, "PHYS": 3, "ART": 4, "GEN-AFF": 5, "ORG-AFF": 6,
                                  "O": 0}, "role_type": {"O": 0},
                "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
                "entity_label": {"O": 0, "B-ORG": 1, "I-ORG": 2, "B-VEH": 3, "I-VEH": 4, "B-FAC": 5, "I-FAC": 6,
                                 "B-WEA": 7, "I-WEA": 8, "B-LOC": 9, "I-LOC": 10, "B-GPE": 11, "I-GPE": 12, "B-PER": 13,
                                 "I-PER": 14}, "trigger_label": {"O": 0}},
    'ace05-e': {"entity_type": {"LOC": 1, "WEA": 2, "FAC": 3, "ORG": 4, "GPE": 5, "PER": 6, "VEH": 7, "O": 0},
                "event_type": {"Justice:Pardon": 1, "Business:Merge-Org": 2, "Justice:Sue": 3, "Justice:Sentence": 4,
                               "Conflict:Attack": 5, "Life:Divorce": 6, "Justice:Arrest-Jail": 7,
                               "Business:Declare-Bankruptcy": 8, "Life:Injure": 9, "Justice:Execute": 10,
                               "Contact:Phone-Write": 11, "Life:Be-Born": 12, "Justice:Fine": 13,
                               "Justice:Charge-Indict": 14, "Justice:Release-Parole": 15,
                               "Transaction:Transfer-Money": 16, "Life:Die": 17, "Justice:Acquit": 18, "Life:Marry": 19,
                               "Justice:Appeal": 20, "Personnel:Elect": 21, "Justice:Convict": 22,
                               "Justice:Extradite": 23, "Personnel:Nominate": 24, "Conflict:Demonstrate": 25,
                               "Business:End-Org": 26, "Personnel:Start-Position": 27, "Movement:Transport": 28,
                               "Contact:Meet": 29, "Transaction:Transfer-Ownership": 30, "Justice:Trial-Hearing": 31,
                               "Personnel:End-Position": 32, "Business:Start-Org": 33, "O": 0},
                "relation_type": {"ART": 1, "PHYS": 2, "ORG-AFF": 3, "PART-WHOLE": 4, "GEN-AFF": 5, "PER-SOC": 6,
                                  "O": 0},
                "role_type": {"Destination": 1, "Place": 2, "Victim": 3, "Plaintiff": 4, "Seller": 5, "Entity": 6,
                              "Beneficiary": 7, "Org": 8, "Instrument": 9, "Buyer": 10, "Agent": 11, "Prosecutor": 12,
                              "Vehicle": 13, "Origin": 14, "Defendant": 15, "Artifact": 16, "Adjudicator": 17,
                              "Attacker": 18, "Person": 19, "Target": 20, "Giver": 21, "Recipient": 22, "O": 0},
                "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
                "entity_label": {"O": 0, "B-LOC": 1, "I-LOC": 2, "B-WEA": 3, "I-WEA": 4, "B-FAC": 5, "I-FAC": 6,
                                 "B-ORG": 7, "I-ORG": 8, "B-GPE": 9, "I-GPE": 10, "B-PER": 11, "I-PER": 12, "B-VEH": 13,
                                 "I-VEH": 14},
                "trigger_label": {"O": 0, "B-Justice:Pardon": 1, "I-Justice:Pardon": 2, "B-Business:Merge-Org": 3,
                                  "I-Business:Merge-Org": 4, "B-Justice:Sue": 5, "I-Justice:Sue": 6,
                                  "B-Justice:Sentence": 7, "I-Justice:Sentence": 8, "B-Conflict:Attack": 9,
                                  "I-Conflict:Attack": 10, "B-Life:Divorce": 11, "I-Life:Divorce": 12,
                                  "B-Justice:Arrest-Jail": 13, "I-Justice:Arrest-Jail": 14,
                                  "B-Business:Declare-Bankruptcy": 15, "I-Business:Declare-Bankruptcy": 16,
                                  "B-Life:Injure": 17, "I-Life:Injure": 18, "B-Justice:Execute": 19,
                                  "I-Justice:Execute": 20, "B-Contact:Phone-Write": 21, "I-Contact:Phone-Write": 22,
                                  "B-Life:Be-Born": 23, "I-Life:Be-Born": 24, "B-Justice:Fine": 25,
                                  "I-Justice:Fine": 26, "B-Justice:Charge-Indict": 27, "I-Justice:Charge-Indict": 28,
                                  "B-Justice:Release-Parole": 29, "I-Justice:Release-Parole": 30,
                                  "B-Transaction:Transfer-Money": 31, "I-Transaction:Transfer-Money": 32,
                                  "B-Life:Die": 33, "I-Life:Die": 34, "B-Justice:Acquit": 35, "I-Justice:Acquit": 36,
                                  "B-Life:Marry": 37, "I-Life:Marry": 38, "B-Justice:Appeal": 39,
                                  "I-Justice:Appeal": 40, "B-Personnel:Elect": 41, "I-Personnel:Elect": 42,
                                  "B-Justice:Convict": 43, "I-Justice:Convict": 44, "B-Justice:Extradite": 45,
                                  "I-Justice:Extradite": 46, "B-Personnel:Nominate": 47, "I-Personnel:Nominate": 48,
                                  "B-Conflict:Demonstrate": 49, "I-Conflict:Demonstrate": 50, "B-Business:End-Org": 51,
                                  "I-Business:End-Org": 52, "B-Personnel:Start-Position": 53,
                                  "I-Personnel:Start-Position": 54, "B-Movement:Transport": 55,
                                  "I-Movement:Transport": 56, "B-Contact:Meet": 57, "I-Contact:Meet": 58,
                                  "B-Transaction:Transfer-Ownership": 59, "I-Transaction:Transfer-Ownership": 60,
                                  "B-Justice:Trial-Hearing": 61, "I-Justice:Trial-Hearing": 62,
                                  "B-Personnel:End-Position": 63, "I-Personnel:End-Position": 64,
                                  "B-Business:Start-Org": 65, "I-Business:Start-Org": 66}},
    'ace05-e+': {"entity_type": {"PER": 1, "WEA": 2, "LOC": 3, "GPE": 4, "ORG": 5, "VEH": 6, "FAC": 7, "O": 0},
                 "event_type": {"Justice:Charge-Indict": 1, "Life:Injure": 2, "Transaction:Transfer-Money": 3,
                                "Justice:Fine": 4, "Justice:Release-Parole": 5, "Personnel:End-Position": 6,
                                "Justice:Convict": 7, "Justice:Trial-Hearing": 8, "Contact:Phone-Write": 9,
                                "Personnel:Start-Position": 10, "Personnel:Nominate": 11, "Life:Be-Born": 12,
                                "Business:Start-Org": 13, "Conflict:Demonstrate": 14, "Life:Marry": 15,
                                "Justice:Appeal": 16, "Life:Die": 17, "Justice:Acquit": 18, "Justice:Pardon": 19,
                                "Transaction:Transfer-Ownership": 20, "Conflict:Attack": 21, "Contact:Meet": 22,
                                "Movement:Transport": 23, "Personnel:Elect": 24, "Justice:Sentence": 25,
                                "Business:End-Org": 26, "Justice:Extradite": 27, "Justice:Sue": 28,
                                "Justice:Arrest-Jail": 29, "Justice:Execute": 30, "Business:Merge-Org": 31,
                                "Business:Declare-Bankruptcy": 32, "Life:Divorce": 33, "O": 0},
                 "relation_type": {"ART": 1, "GEN-AFF": 2, "PART-WHOLE": 3, "PHYS": 4, "ORG-AFF": 5, "PER-SOC": 6,
                                   "O": 0},
                 "role_type": {"Entity": 1, "Giver": 2, "Agent": 3, "Destination": 4, "Attacker": 5, "Beneficiary": 6,
                               "Target": 7, "Buyer": 8, "Prosecutor": 9, "Org": 10, "Defendant": 11, "Vehicle": 12,
                               "Place": 13, "Instrument": 14, "Victim": 15, "Recipient": 16, "Artifact": 17,
                               "Adjudicator": 18, "Plaintiff": 19, "Seller": 20, "Person": 21, "Origin": 22, "O": 0},
                 "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
                 "entity_label": {"O": 0, "B-PER": 1, "I-PER": 2, "B-WEA": 3, "I-WEA": 4, "B-LOC": 5, "I-LOC": 6,
                                  "B-GPE": 7, "I-GPE": 8, "B-ORG": 9, "I-ORG": 10, "B-VEH": 11, "I-VEH": 12,
                                  "B-FAC": 13, "I-FAC": 14},
                 "trigger_label": {"O": 0, "B-Justice:Charge-Indict": 1, "I-Justice:Charge-Indict": 2,
                                   "B-Life:Injure": 3, "I-Life:Injure": 4, "B-Transaction:Transfer-Money": 5,
                                   "I-Transaction:Transfer-Money": 6, "B-Justice:Fine": 7, "I-Justice:Fine": 8,
                                   "B-Justice:Release-Parole": 9, "I-Justice:Release-Parole": 10,
                                   "B-Personnel:End-Position": 11, "I-Personnel:End-Position": 12,
                                   "B-Justice:Convict": 13, "I-Justice:Convict": 14, "B-Justice:Trial-Hearing": 15,
                                   "I-Justice:Trial-Hearing": 16, "B-Contact:Phone-Write": 17,
                                   "I-Contact:Phone-Write": 18, "B-Personnel:Start-Position": 19,
                                   "I-Personnel:Start-Position": 20, "B-Personnel:Nominate": 21,
                                   "I-Personnel:Nominate": 22, "B-Life:Be-Born": 23, "I-Life:Be-Born": 24,
                                   "B-Business:Start-Org": 25, "I-Business:Start-Org": 26, "B-Conflict:Demonstrate": 27,
                                   "I-Conflict:Demonstrate": 28, "B-Life:Marry": 29, "I-Life:Marry": 30,
                                   "B-Justice:Appeal": 31, "I-Justice:Appeal": 32, "B-Life:Die": 33, "I-Life:Die": 34,
                                   "B-Justice:Acquit": 35, "I-Justice:Acquit": 36, "B-Justice:Pardon": 37,
                                   "I-Justice:Pardon": 38, "B-Transaction:Transfer-Ownership": 39,
                                   "I-Transaction:Transfer-Ownership": 40, "B-Conflict:Attack": 41,
                                   "I-Conflict:Attack": 42, "B-Contact:Meet": 43, "I-Contact:Meet": 44,
                                   "B-Movement:Transport": 45, "I-Movement:Transport": 46, "B-Personnel:Elect": 47,
                                   "I-Personnel:Elect": 48, "B-Justice:Sentence": 49, "I-Justice:Sentence": 50,
                                   "B-Business:End-Org": 51, "I-Business:End-Org": 52, "B-Justice:Extradite": 53,
                                   "I-Justice:Extradite": 54, "B-Justice:Sue": 55, "I-Justice:Sue": 56,
                                   "B-Justice:Arrest-Jail": 57, "I-Justice:Arrest-Jail": 58, "B-Justice:Execute": 59,
                                   "I-Justice:Execute": 60, "B-Business:Merge-Org": 61, "I-Business:Merge-Org": 62,
                                   "B-Business:Declare-Bankruptcy": 63, "I-Business:Declare-Bankruptcy": 64,
                                   "B-Life:Divorce": 65, "I-Life:Divorce": 66},
                 "deprel_type": {'_': 0, 'root': 1, 'punct': 2, 'flat': 3, 'amod': 4, 'nsubj': 5,
                                 'parataxis': 6, 'obj': 7, 'det': 8, 'appos': 9, 'case': 10, 'obl': 11,
                                 'nmod': 12, 'aux': 13, 'iobj': 14, 'mark': 15, 'acl': 16, 'ccomp': 17,
                                 'compound:prt': 18, 'nummod': 19, 'nsubj:pass': 20, 'aux:pass': 21, 'cop': 22, 'compound': 23,
                                 'advmod': 24, 'advcl': 25, 'nmod:poss': 26, 'cc': 27, 'conj': 28, 'xcomp': 29,
                                 'acl:relcl': 30, 'expl': 31, 'fixed': 32, 'det:predet': 33, 'obl:npmod': 34, 'obl:tmod': 35,
                                 'nmod:tmod': 36, 'csubj': 37, 'orphan': 38, 'csubj:pass': 39, 'vocative': 40, 'nmod:npmod': 41,
                                 'list': 42, 'discourse': 43, 'dislocated': 44, 'reparandum': 45, 'cc:preconj': 46, 'flat:foreign': 47,
                                 'goeswith': 48, 'dep': 49}},
    'ere-en': {"entity_type": {"FAC": 1, "WEA": 2, "LOC": 3, "VEH": 4, "GPE": 5, "ORG": 6, "PER": 7, "O": 0},
               "event_type": {"Personnel:End-Position": 1, "Justice:Pardon": 2, "Contact:Meet": 3,
                              "Personnel:Nominate": 4, "Justice:Execute": 5, "Justice:Sue": 6,
                              "Personnel:Start-Position": 7, "Justice:Sentence": 8, "Justice:Charge-Indict": 9,
                              "Contact:Correspondence": 10, "Business:Merge-Org": 11, "Transaction:Transfer-Money": 12,
                              "Conflict:Demonstrate": 13, "Movement:Transport-Person": 14,
                              "Business:Declare-Bankruptcy": 15, "Movement:Transport": 16, "Justice:Trial-Hearing": 17,
                              "Life:Be-Born": 18, "Manufacture:Artifact": 19, "Justice:Extradite": 20,
                              "Contact:Broadcast": 21, "Business:Start-Org": 22, "Life:Divorce": 23,
                              "Justice:Arrest-Jail": 24, "Conflict:Attack": 25, "Justice:Acquit": 26, "Life:Die": 27,
                              "Business:End-Org": 28, "Life:Marry": 29, "Justice:Convict": 30, "Justice:Fine": 31,
                              "Contact:Contact": 32, "Personnel:Elect": 33, "Justice:Release-Parole": 34,
                              "Transaction:Transfer-Ownership": 35, "Transaction:Transaction": 36, "Life:Injure": 37,
                              "Justice:Appeal": 38, "O": 0},
               "relation_type": {"ORG-AFF": 1, "GEN-AFF": 2, "PHYS": 3, "PER-SOC": 4, "PART-WHOLE": 5, "O": 0},
               "role_type": {"Defendant": 1, "Beneficiary": 2, "Audience": 3, "Giver": 4, "Victim": 5, "Adjudicator": 6,
                             "Entity": 7, "Instrument": 8, "Plaintiff": 9, "Destination": 10, "Org": 11,
                             "Prosecutor": 12, "Recipient": 13, "Person": 14, "Target": 15, "Artifact": 16, "Thing": 17,
                             "Place": 18, "Origin": 19, "Agent": 20, "Attacker": 21, "O": 0},
               "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
               "entity_label": {"O": 0, "B-FAC": 1, "I-FAC": 2, "B-WEA": 3, "I-WEA": 4, "B-LOC": 5, "I-LOC": 6,
                                "B-VEH": 7, "I-VEH": 8, "B-GPE": 9, "I-GPE": 10, "B-ORG": 11, "I-ORG": 12, "B-PER": 13,
                                "I-PER": 14},
               "trigger_label": {"O": 0, "B-Personnel:End-Position": 1, "I-Personnel:End-Position": 2,
                                 "B-Justice:Pardon": 3, "I-Justice:Pardon": 4, "B-Contact:Meet": 5, "I-Contact:Meet": 6,
                                 "B-Personnel:Nominate": 7, "I-Personnel:Nominate": 8, "B-Justice:Execute": 9,
                                 "I-Justice:Execute": 10, "B-Justice:Sue": 11, "I-Justice:Sue": 12,
                                 "B-Personnel:Start-Position": 13, "I-Personnel:Start-Position": 14,
                                 "B-Justice:Sentence": 15, "I-Justice:Sentence": 16, "B-Justice:Charge-Indict": 17,
                                 "I-Justice:Charge-Indict": 18, "B-Contact:Correspondence": 19,
                                 "I-Contact:Correspondence": 20, "B-Business:Merge-Org": 21, "I-Business:Merge-Org": 22,
                                 "B-Transaction:Transfer-Money": 23, "I-Transaction:Transfer-Money": 24,
                                 "B-Conflict:Demonstrate": 25, "I-Conflict:Demonstrate": 26,
                                 "B-Movement:Transport-Person": 27, "I-Movement:Transport-Person": 28,
                                 "B-Business:Declare-Bankruptcy": 29, "I-Business:Declare-Bankruptcy": 30,
                                 "B-Movement:Transport": 31, "I-Movement:Transport": 32, "B-Justice:Trial-Hearing": 33,
                                 "I-Justice:Trial-Hearing": 34, "B-Life:Be-Born": 35, "I-Life:Be-Born": 36,
                                 "B-Manufacture:Artifact": 37, "I-Manufacture:Artifact": 38, "B-Justice:Extradite": 39,
                                 "I-Justice:Extradite": 40, "B-Contact:Broadcast": 41, "I-Contact:Broadcast": 42,
                                 "B-Business:Start-Org": 43, "I-Business:Start-Org": 44, "B-Life:Divorce": 45,
                                 "I-Life:Divorce": 46, "B-Justice:Arrest-Jail": 47, "I-Justice:Arrest-Jail": 48,
                                 "B-Conflict:Attack": 49, "I-Conflict:Attack": 50, "B-Justice:Acquit": 51,
                                 "I-Justice:Acquit": 52, "B-Life:Die": 53, "I-Life:Die": 54, "B-Business:End-Org": 55,
                                 "I-Business:End-Org": 56, "B-Life:Marry": 57, "I-Life:Marry": 58,
                                 "B-Justice:Convict": 59, "I-Justice:Convict": 60, "B-Justice:Fine": 61,
                                 "I-Justice:Fine": 62, "B-Contact:Contact": 63, "I-Contact:Contact": 64,
                                 "B-Personnel:Elect": 65, "I-Personnel:Elect": 66, "B-Justice:Release-Parole": 67,
                                 "I-Justice:Release-Parole": 68, "B-Transaction:Transfer-Ownership": 69,
                                 "I-Transaction:Transfer-Ownership": 70, "B-Transaction:Transaction": 71,
                                 "I-Transaction:Transaction": 72, "B-Life:Injure": 73, "I-Life:Injure": 74,
                                 "B-Justice:Appeal": 75, "I-Justice:Appeal": 76}},
    'ace05-cn': {"entity_type": {"GPE": 1, "ORG": 2, "PER": 3, "WEA": 4, "FAC": 5, "VEH": 6, "LOC": 7, "O": 0},
                 "event_type": {"Life:Divorce": 1, "Life:Marry": 2, "Justice:Convict": 3, "Justice:Execute": 4,
                                "Justice:Charge-Indict": 5, "Conflict:Demonstrate": 6, "Business:Merge-Org": 7,
                                "Justice:Trial-Hearing": 8, "Justice:Extradite": 9, "Personnel:End-Position": 10,
                                "Business:End-Org": 11, "Justice:Sentence": 12, "Business:Start-Org": 13,
                                "Transaction:Transfer-Ownership": 14, "Movement:Transport": 15,
                                "Personnel:Nominate": 16, "Justice:Acquit": 17, "Life:Be-Born": 18,
                                "Personnel:Elect": 19, "Life:Die": 20, "Justice:Sue": 21, "Justice:Release-Parole": 22,
                                "Business:Declare-Bankruptcy": 23, "Personnel:Start-Position": 24, "Justice:Pardon": 25,
                                "Contact:Meet": 26, "Justice:Fine": 27, "Life:Injure": 28,
                                "Transaction:Transfer-Money": 29, "Conflict:Attack": 30, "Contact:Phone-Write": 31,
                                "Justice:Arrest-Jail": 32, "Justice:Appeal": 33, "O": 0},
                 "relation_type": {"PHYS": 1, "PART-WHOLE": 2, "ART": 3, "PER-SOC": 4, "GEN-AFF": 5, "ORG-AFF": 6,
                                   "O": 0},
                 "role_type": {"Recipient": 1, "Buyer": 2, "Victim": 3, "Instrument": 4, "Agent": 5, "Artifact": 6,
                               "Target": 7, "Plaintiff": 8, "Prosecutor": 9, "Attacker": 10, "Origin": 11,
                               "Adjudicator": 12, "Defendant": 13, "Vehicle": 14, "Giver": 15, "Place": 16,
                               "Person": 17, "Destination": 18, "Beneficiary": 19, "Seller": 20, "Org": 21,
                               "Entity": 22, "O": 0}, "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
                 "entity_label": {"O": 0, "B-GPE": 1, "I-GPE": 2, "B-ORG": 3, "I-ORG": 4, "B-PER": 5, "I-PER": 6,
                                  "B-WEA": 7, "I-WEA": 8, "B-FAC": 9, "I-FAC": 10, "B-VEH": 11, "I-VEH": 12,
                                  "B-LOC": 13, "I-LOC": 14},
                 "trigger_label": {"O": 0, "B-Life:Divorce": 1, "I-Life:Divorce": 2, "B-Life:Marry": 3,
                                   "I-Life:Marry": 4, "B-Justice:Convict": 5, "I-Justice:Convict": 6,
                                   "B-Justice:Execute": 7, "I-Justice:Execute": 8, "B-Justice:Charge-Indict": 9,
                                   "I-Justice:Charge-Indict": 10, "B-Conflict:Demonstrate": 11,
                                   "I-Conflict:Demonstrate": 12, "B-Business:Merge-Org": 13, "I-Business:Merge-Org": 14,
                                   "B-Justice:Trial-Hearing": 15, "I-Justice:Trial-Hearing": 16,
                                   "B-Justice:Extradite": 17, "I-Justice:Extradite": 18, "B-Personnel:End-Position": 19,
                                   "I-Personnel:End-Position": 20, "B-Business:End-Org": 21, "I-Business:End-Org": 22,
                                   "B-Justice:Sentence": 23, "I-Justice:Sentence": 24, "B-Business:Start-Org": 25,
                                   "I-Business:Start-Org": 26, "B-Transaction:Transfer-Ownership": 27,
                                   "I-Transaction:Transfer-Ownership": 28, "B-Movement:Transport": 29,
                                   "I-Movement:Transport": 30, "B-Personnel:Nominate": 31, "I-Personnel:Nominate": 32,
                                   "B-Justice:Acquit": 33, "I-Justice:Acquit": 34, "B-Life:Be-Born": 35,
                                   "I-Life:Be-Born": 36, "B-Personnel:Elect": 37, "I-Personnel:Elect": 38,
                                   "B-Life:Die": 39, "I-Life:Die": 40, "B-Justice:Sue": 41, "I-Justice:Sue": 42,
                                   "B-Justice:Release-Parole": 43, "I-Justice:Release-Parole": 44,
                                   "B-Business:Declare-Bankruptcy": 45, "I-Business:Declare-Bankruptcy": 46,
                                   "B-Personnel:Start-Position": 47, "I-Personnel:Start-Position": 48,
                                   "B-Justice:Pardon": 49, "I-Justice:Pardon": 50, "B-Contact:Meet": 51,
                                   "I-Contact:Meet": 52, "B-Justice:Fine": 53, "I-Justice:Fine": 54,
                                   "B-Life:Injure": 55, "I-Life:Injure": 56, "B-Transaction:Transfer-Money": 57,
                                   "I-Transaction:Transfer-Money": 58, "B-Conflict:Attack": 59, "I-Conflict:Attack": 60,
                                   "B-Contact:Phone-Write": 61, "I-Contact:Phone-Write": 62,
                                   "B-Justice:Arrest-Jail": 63, "I-Justice:Arrest-Jail": 64, "B-Justice:Appeal": 65,
                                   "I-Justice:Appeal": 66}},
    'ace05-cn+en': {"entity_type": {"ORG": 1, "VEH": 2, "WEA": 3, "PER": 4, "LOC": 5, "FAC": 6, "GPE": 7, "O": 0},
                    "event_type": {"Personnel:Nominate": 1, "Business:Merge-Org": 2, "Personnel:Elect": 3,
                                   "Justice:Acquit": 4, "Justice:Convict": 5, "Life:Be-Born": 6,
                                   "Justice:Charge-Indict": 7, "Life:Marry": 8, "Justice:Arrest-Jail": 9,
                                   "Justice:Sue": 10, "Conflict:Attack": 11, "Life:Injure": 12, "Justice:Fine": 13,
                                   "Justice:Release-Parole": 14, "Contact:Phone-Write": 15, "Conflict:Demonstrate": 16,
                                   "Movement:Transport": 17, "Business:Start-Org": 18, "Business:End-Org": 19,
                                   "Personnel:Start-Position": 20, "Transaction:Transfer-Money": 21,
                                   "Business:Declare-Bankruptcy": 22, "Personnel:End-Position": 23,
                                   "Justice:Sentence": 24, "Life:Divorce": 25, "Justice:Appeal": 26,
                                   "Transaction:Transfer-Ownership": 27, "Life:Die": 28, "Justice:Extradite": 29,
                                   "Justice:Pardon": 30, "Contact:Meet": 31, "Justice:Trial-Hearing": 32,
                                   "Justice:Execute": 33, "O": 0},
                    "relation_type": {"ORG-AFF": 1, "PER-SOC": 2, "PHYS": 3, "PART-WHOLE": 4, "ART": 5, "GEN-AFF": 6,
                                      "O": 0},
                    "role_type": {"Seller": 1, "Recipient": 2, "Adjudicator": 3, "Plaintiff": 4, "Artifact": 5,
                                  "Origin": 6, "Entity": 7, "Victim": 8, "Target": 9, "Attacker": 10, "Defendant": 11,
                                  "Destination": 12, "Prosecutor": 13, "Place": 14, "Person": 15, "Agent": 16,
                                  "Beneficiary": 17, "Vehicle": 18, "Giver": 19, "Org": 20, "Instrument": 21,
                                  "Buyer": 22, "O": 0}, "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
                    "entity_label": {"O": 0, "B-ORG": 1, "I-ORG": 2, "B-VEH": 3, "I-VEH": 4, "B-WEA": 5, "I-WEA": 6,
                                     "B-PER": 7, "I-PER": 8, "B-LOC": 9, "I-LOC": 10, "B-FAC": 11, "I-FAC": 12,
                                     "B-GPE": 13, "I-GPE": 14},
                    "trigger_label": {"O": 0, "B-Personnel:Nominate": 1, "I-Personnel:Nominate": 2,
                                      "B-Business:Merge-Org": 3, "I-Business:Merge-Org": 4, "B-Personnel:Elect": 5,
                                      "I-Personnel:Elect": 6, "B-Justice:Acquit": 7, "I-Justice:Acquit": 8,
                                      "B-Justice:Convict": 9, "I-Justice:Convict": 10, "B-Life:Be-Born": 11,
                                      "I-Life:Be-Born": 12, "B-Justice:Charge-Indict": 13,
                                      "I-Justice:Charge-Indict": 14, "B-Life:Marry": 15, "I-Life:Marry": 16,
                                      "B-Justice:Arrest-Jail": 17, "I-Justice:Arrest-Jail": 18, "B-Justice:Sue": 19,
                                      "I-Justice:Sue": 20, "B-Conflict:Attack": 21, "I-Conflict:Attack": 22,
                                      "B-Life:Injure": 23, "I-Life:Injure": 24, "B-Justice:Fine": 25,
                                      "I-Justice:Fine": 26, "B-Justice:Release-Parole": 27,
                                      "I-Justice:Release-Parole": 28, "B-Contact:Phone-Write": 29,
                                      "I-Contact:Phone-Write": 30, "B-Conflict:Demonstrate": 31,
                                      "I-Conflict:Demonstrate": 32, "B-Movement:Transport": 33,
                                      "I-Movement:Transport": 34, "B-Business:Start-Org": 35,
                                      "I-Business:Start-Org": 36, "B-Business:End-Org": 37, "I-Business:End-Org": 38,
                                      "B-Personnel:Start-Position": 39, "I-Personnel:Start-Position": 40,
                                      "B-Transaction:Transfer-Money": 41, "I-Transaction:Transfer-Money": 42,
                                      "B-Business:Declare-Bankruptcy": 43, "I-Business:Declare-Bankruptcy": 44,
                                      "B-Personnel:End-Position": 45, "I-Personnel:End-Position": 46,
                                      "B-Justice:Sentence": 47, "I-Justice:Sentence": 48, "B-Life:Divorce": 49,
                                      "I-Life:Divorce": 50, "B-Justice:Appeal": 51, "I-Justice:Appeal": 52,
                                      "B-Transaction:Transfer-Ownership": 53, "I-Transaction:Transfer-Ownership": 54,
                                      "B-Life:Die": 55, "I-Life:Die": 56, "B-Justice:Extradite": 57,
                                      "I-Justice:Extradite": 58, "B-Justice:Pardon": 59, "I-Justice:Pardon": 60,
                                      "B-Contact:Meet": 61, "I-Contact:Meet": 62, "B-Justice:Trial-Hearing": 63,
                                      "I-Justice:Trial-Hearing": 64, "B-Justice:Execute": 65, "I-Justice:Execute": 66}},
    'ere-es': {"entity_type": {"WEA": 1, "PER": 2, "LOC": 3, "GPE": 4, "VEH": 5, "ORG": 6, "FAC": 7, "O": 0},
               "event_type": {"Justice:Acquit": 1, "Justice:Appeal": 2, "Justice:Execute": 3, "Movement:Transport": 4,
                              "Justice:Sue": 5, "Justice:Trial-Hearing": 6, "Transaction:Transfer-Money": 7,
                              "Manufacture:Artifact": 8, "Contact:Correspondence": 9, "Justice:Extradite": 10,
                              "Personnel:Elect": 11, "Contact:Meet": 12, "Business:Declare-Bankruptcy": 13,
                              "Life:Injure": 14, "Contact:Contact": 15, "Justice:Convict": 16,
                              "Conflict:Demonstrate": 17, "Conflict:Attack": 18, "Justice:Sentence": 19,
                              "Personnel:Nominate": 20, "Contact:Broadcast": 21, "Personnel:End-Position": 22,
                              "Justice:Arrest-Jail": 23, "Business:Start-Org": 24, "Justice:Charge-Indict": 25,
                              "Life:Be-Born": 26, "Justice:Fine": 27, "Business:End-Org": 28,
                              "Justice:Release-Parole": 29, "Life:Die": 30, "Transaction:Transfer-Ownership": 31,
                              "Justice:Pardon": 32, "Life:Marry": 33, "Movement:Transport-Person": 34,
                              "Personnel:Start-Position": 35, "Transaction:Transaction": 36, "O": 0},
               "relation_type": {"PHYS": 1, "GEN-AFF": 2, "PER-SOC": 3, "PART-WHOLE": 4, "ORG-AFF": 5, "O": 0},
               "role_type": {"Person": 1, "Org": 2, "Victim": 3, "Thing": 4, "Attacker": 5, "Beneficiary": 6,
                             "Target": 7, "Agent": 8, "Plaintiff": 9, "Entity": 10, "Prosecutor": 11, "Destination": 12,
                             "Artifact": 13, "Audience": 14, "Giver": 15, "Instrument": 16, "Recipient": 17,
                             "Origin": 18, "Defendant": 19, "Place": 20, "Adjudicator": 21, "O": 0},
               "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
               "entity_label": {"O": 0, "B-WEA": 1, "I-WEA": 2, "B-PER": 3, "I-PER": 4, "B-LOC": 5, "I-LOC": 6,
                                "B-GPE": 7, "I-GPE": 8, "B-VEH": 9, "I-VEH": 10, "B-ORG": 11, "I-ORG": 12, "B-FAC": 13,
                                "I-FAC": 14},
               "trigger_label": {"O": 0, "B-Justice:Acquit": 1, "I-Justice:Acquit": 2, "B-Justice:Appeal": 3,
                                 "I-Justice:Appeal": 4, "B-Justice:Execute": 5, "I-Justice:Execute": 6,
                                 "B-Movement:Transport": 7, "I-Movement:Transport": 8, "B-Justice:Sue": 9,
                                 "I-Justice:Sue": 10, "B-Justice:Trial-Hearing": 11, "I-Justice:Trial-Hearing": 12,
                                 "B-Transaction:Transfer-Money": 13, "I-Transaction:Transfer-Money": 14,
                                 "B-Manufacture:Artifact": 15, "I-Manufacture:Artifact": 16,
                                 "B-Contact:Correspondence": 17, "I-Contact:Correspondence": 18,
                                 "B-Justice:Extradite": 19, "I-Justice:Extradite": 20, "B-Personnel:Elect": 21,
                                 "I-Personnel:Elect": 22, "B-Contact:Meet": 23, "I-Contact:Meet": 24,
                                 "B-Business:Declare-Bankruptcy": 25, "I-Business:Declare-Bankruptcy": 26,
                                 "B-Life:Injure": 27, "I-Life:Injure": 28, "B-Contact:Contact": 29,
                                 "I-Contact:Contact": 30, "B-Justice:Convict": 31, "I-Justice:Convict": 32,
                                 "B-Conflict:Demonstrate": 33, "I-Conflict:Demonstrate": 34, "B-Conflict:Attack": 35,
                                 "I-Conflict:Attack": 36, "B-Justice:Sentence": 37, "I-Justice:Sentence": 38,
                                 "B-Personnel:Nominate": 39, "I-Personnel:Nominate": 40, "B-Contact:Broadcast": 41,
                                 "I-Contact:Broadcast": 42, "B-Personnel:End-Position": 43,
                                 "I-Personnel:End-Position": 44, "B-Justice:Arrest-Jail": 45,
                                 "I-Justice:Arrest-Jail": 46, "B-Business:Start-Org": 47, "I-Business:Start-Org": 48,
                                 "B-Justice:Charge-Indict": 49, "I-Justice:Charge-Indict": 50, "B-Life:Be-Born": 51,
                                 "I-Life:Be-Born": 52, "B-Justice:Fine": 53, "I-Justice:Fine": 54,
                                 "B-Business:End-Org": 55, "I-Business:End-Org": 56, "B-Justice:Release-Parole": 57,
                                 "I-Justice:Release-Parole": 58, "B-Life:Die": 59, "I-Life:Die": 60,
                                 "B-Transaction:Transfer-Ownership": 61, "I-Transaction:Transfer-Ownership": 62,
                                 "B-Justice:Pardon": 63, "I-Justice:Pardon": 64, "B-Life:Marry": 65, "I-Life:Marry": 66,
                                 "B-Movement:Transport-Person": 67, "I-Movement:Transport-Person": 68,
                                 "B-Personnel:Start-Position": 69, "I-Personnel:Start-Position": 70,
                                 "B-Transaction:Transaction": 71, "I-Transaction:Transaction": 72}},
    'ere-es+en': {"entity_type": {"FAC": 1, "ORG": 2, "GPE": 3, "VEH": 4, "LOC": 5, "PER": 6, "WEA": 7, "O": 0},
                  "event_type": {"Manufacture:Artifact": 1, "Personnel:Nominate": 2, "Personnel:End-Position": 3,
                                 "Conflict:Attack": 4, "Business:End-Org": 5, "Justice:Sentence": 6,
                                 "Contact:Contact": 7, "Contact:Broadcast": 8, "Justice:Arrest-Jail": 9,
                                 "Transaction:Transaction": 10, "Conflict:Demonstrate": 11, "Justice:Execute": 12,
                                 "Business:Merge-Org": 13, "Personnel:Start-Position": 14, "Justice:Trial-Hearing": 15,
                                 "Justice:Appeal": 16, "Life:Divorce": 17, "Life:Die": 18, "Contact:Correspondence": 19,
                                 "Contact:Meet": 20, "Business:Start-Org": 21, "Justice:Sue": 22,
                                 "Business:Declare-Bankruptcy": 23, "Transaction:Transfer-Ownership": 24,
                                 "Movement:Transport": 25, "Justice:Release-Parole": 26, "Justice:Extradite": 27,
                                 "Life:Marry": 28, "Transaction:Transfer-Money": 29, "Personnel:Elect": 30,
                                 "Justice:Acquit": 31, "Justice:Charge-Indict": 32, "Life:Be-Born": 33,
                                 "Movement:Transport-Person": 34, "Justice:Fine": 35, "Life:Injure": 36,
                                 "Justice:Pardon": 37, "Justice:Convict": 38, "O": 0},
                  "relation_type": {"GEN-AFF": 1, "PHYS": 2, "PER-SOC": 3, "PART-WHOLE": 4, "ORG-AFF": 5, "O": 0},
                  "role_type": {"Entity": 1, "Recipient": 2, "Defendant": 3, "Audience": 4, "Agent": 5,
                                "Adjudicator": 6, "Giver": 7, "Target": 8, "Origin": 9, "Artifact": 10,
                                "Instrument": 11, "Attacker": 12, "Place": 13, "Org": 14, "Destination": 15,
                                "Victim": 16, "Prosecutor": 17, "Beneficiary": 18, "Person": 19, "Plaintiff": 20,
                                "Thing": 21, "O": 0}, "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
                  "entity_label": {"O": 0, "B-FAC": 1, "I-FAC": 2, "B-ORG": 3, "I-ORG": 4, "B-GPE": 5, "I-GPE": 6,
                                   "B-VEH": 7, "I-VEH": 8, "B-LOC": 9, "I-LOC": 10, "B-PER": 11, "I-PER": 12,
                                   "B-WEA": 13, "I-WEA": 14},
                  "trigger_label": {"O": 0, "B-Manufacture:Artifact": 1, "I-Manufacture:Artifact": 2,
                                    "B-Personnel:Nominate": 3, "I-Personnel:Nominate": 4, "B-Personnel:End-Position": 5,
                                    "I-Personnel:End-Position": 6, "B-Conflict:Attack": 7, "I-Conflict:Attack": 8,
                                    "B-Business:End-Org": 9, "I-Business:End-Org": 10, "B-Justice:Sentence": 11,
                                    "I-Justice:Sentence": 12, "B-Contact:Contact": 13, "I-Contact:Contact": 14,
                                    "B-Contact:Broadcast": 15, "I-Contact:Broadcast": 16, "B-Justice:Arrest-Jail": 17,
                                    "I-Justice:Arrest-Jail": 18, "B-Transaction:Transaction": 19,
                                    "I-Transaction:Transaction": 20, "B-Conflict:Demonstrate": 21,
                                    "I-Conflict:Demonstrate": 22, "B-Justice:Execute": 23, "I-Justice:Execute": 24,
                                    "B-Business:Merge-Org": 25, "I-Business:Merge-Org": 26,
                                    "B-Personnel:Start-Position": 27, "I-Personnel:Start-Position": 28,
                                    "B-Justice:Trial-Hearing": 29, "I-Justice:Trial-Hearing": 30,
                                    "B-Justice:Appeal": 31, "I-Justice:Appeal": 32, "B-Life:Divorce": 33,
                                    "I-Life:Divorce": 34, "B-Life:Die": 35, "I-Life:Die": 36,
                                    "B-Contact:Correspondence": 37, "I-Contact:Correspondence": 38,
                                    "B-Contact:Meet": 39, "I-Contact:Meet": 40, "B-Business:Start-Org": 41,
                                    "I-Business:Start-Org": 42, "B-Justice:Sue": 43, "I-Justice:Sue": 44,
                                    "B-Business:Declare-Bankruptcy": 45, "I-Business:Declare-Bankruptcy": 46,
                                    "B-Transaction:Transfer-Ownership": 47, "I-Transaction:Transfer-Ownership": 48,
                                    "B-Movement:Transport": 49, "I-Movement:Transport": 50,
                                    "B-Justice:Release-Parole": 51, "I-Justice:Release-Parole": 52,
                                    "B-Justice:Extradite": 53, "I-Justice:Extradite": 54, "B-Life:Marry": 55,
                                    "I-Life:Marry": 56, "B-Transaction:Transfer-Money": 57,
                                    "I-Transaction:Transfer-Money": 58, "B-Personnel:Elect": 59,
                                    "I-Personnel:Elect": 60, "B-Justice:Acquit": 61, "I-Justice:Acquit": 62,
                                    "B-Justice:Charge-Indict": 63, "I-Justice:Charge-Indict": 64, "B-Life:Be-Born": 65,
                                    "I-Life:Be-Born": 66, "B-Movement:Transport-Person": 67,
                                    "I-Movement:Transport-Person": 68, "B-Justice:Fine": 69, "I-Justice:Fine": 70,
                                    "B-Life:Injure": 71, "I-Life:Injure": 72, "B-Justice:Pardon": 73,
                                    "I-Justice:Pardon": 74, "B-Justice:Convict": 75, "I-Justice:Convict": 76}},
    'live': {"entity_type": {"PER": 1, "WEA": 2, "LOC": 3, "GPE": 4, "ORG": 5, "VEH": 6, "FAC": 7, "O": 0},
             "event_type": {"Justice:Charge-Indict": 1, "Life:Injure": 2, "Transaction:Transfer-Money": 3,
                            "Justice:Fine": 4, "Justice:Release-Parole": 5, "Personnel:End-Position": 6,
                            "Justice:Convict": 7, "Justice:Trial-Hearing": 8, "Contact:Phone-Write": 9,
                            "Personnel:Start-Position": 10, "Personnel:Nominate": 11, "Life:Be-Born": 12,
                            "Business:Start-Org": 13, "Conflict:Demonstrate": 14, "Life:Marry": 15,
                            "Justice:Appeal": 16, "Life:Die": 17, "Justice:Acquit": 18, "Justice:Pardon": 19,
                            "Transaction:Transfer-Ownership": 20, "Conflict:Attack": 21, "Contact:Meet": 22,
                            "Movement:Transport": 23, "Personnel:Elect": 24, "Justice:Sentence": 25,
                            "Business:End-Org": 26, "Justice:Extradite": 27, "Justice:Sue": 28,
                            "Justice:Arrest-Jail": 29, "Justice:Execute": 30, "Business:Merge-Org": 31,
                            "Business:Declare-Bankruptcy": 32, "Life:Divorce": 33, "O": 0},
             "relation_type": {"ART": 1, "GEN-AFF": 2, "PART-WHOLE": 3, "PHYS": 4, "ORG-AFF": 5, "PER-SOC": 6,
                               "O": 0},
             "role_type": {"Entity": 1, "Giver": 2, "Agent": 3, "Destination": 4, "Attacker": 5, "Beneficiary": 6,
                           "Target": 7, "Buyer": 8, "Prosecutor": 9, "Org": 10, "Defendant": 11, "Vehicle": 12,
                           "Place": 13, "Instrument": 14, "Victim": 15, "Recipient": 16, "Artifact": 17,
                           "Adjudicator": 18, "Plaintiff": 19, "Seller": 20, "Person": 21, "Origin": 22, "O": 0},
             "mention_type": {"NAM": 0, "NOM": 1, "PRO": 2, "UNK": 3},
             "entity_label": {"O": 0, "B-PER": 1, "I-PER": 2, "B-WEA": 3, "I-WEA": 4, "B-LOC": 5, "I-LOC": 6,
                              "B-GPE": 7, "I-GPE": 8, "B-ORG": 9, "I-ORG": 10, "B-VEH": 11, "I-VEH": 12,
                              "B-FAC": 13, "I-FAC": 14},
             "trigger_label": {"O": 0, "B-Justice:Charge-Indict": 1, "I-Justice:Charge-Indict": 2,
                               "B-Life:Injure": 3, "I-Life:Injure": 4, "B-Transaction:Transfer-Money": 5,
                               "I-Transaction:Transfer-Money": 6, "B-Justice:Fine": 7, "I-Justice:Fine": 8,
                               "B-Justice:Release-Parole": 9, "I-Justice:Release-Parole": 10,
                               "B-Personnel:End-Position": 11, "I-Personnel:End-Position": 12,
                               "B-Justice:Convict": 13, "I-Justice:Convict": 14, "B-Justice:Trial-Hearing": 15,
                               "I-Justice:Trial-Hearing": 16, "B-Contact:Phone-Write": 17,
                               "I-Contact:Phone-Write": 18, "B-Personnel:Start-Position": 19,
                               "I-Personnel:Start-Position": 20, "B-Personnel:Nominate": 21,
                               "I-Personnel:Nominate": 22, "B-Life:Be-Born": 23, "I-Life:Be-Born": 24,
                               "B-Business:Start-Org": 25, "I-Business:Start-Org": 26, "B-Conflict:Demonstrate": 27,
                               "I-Conflict:Demonstrate": 28, "B-Life:Marry": 29, "I-Life:Marry": 30,
                               "B-Justice:Appeal": 31, "I-Justice:Appeal": 32, "B-Life:Die": 33, "I-Life:Die": 34,
                               "B-Justice:Acquit": 35, "I-Justice:Acquit": 36, "B-Justice:Pardon": 37,
                               "I-Justice:Pardon": 38, "B-Transaction:Transfer-Ownership": 39,
                               "I-Transaction:Transfer-Ownership": 40, "B-Conflict:Attack": 41,
                               "I-Conflict:Attack": 42, "B-Contact:Meet": 43, "I-Contact:Meet": 44,
                               "B-Movement:Transport": 45, "I-Movement:Transport": 46, "B-Personnel:Elect": 47,
                               "I-Personnel:Elect": 48, "B-Justice:Sentence": 49, "I-Justice:Sentence": 50,
                               "B-Business:End-Org": 51, "I-Business:End-Org": 52, "B-Justice:Extradite": 53,
                               "I-Justice:Extradite": 54, "B-Justice:Sue": 55, "I-Justice:Sue": 56,
                               "B-Justice:Arrest-Jail": 57, "I-Justice:Arrest-Jail": 58, "B-Justice:Execute": 59,
                               "I-Justice:Execute": 60, "B-Business:Merge-Org": 61, "I-Business:Merge-Org": 62,
                               "B-Business:Declare-Bankruptcy": 63, "I-Business:Declare-Bankruptcy": 64,
                               "B-Life:Divorce": 65, "I-Life:Divorce": 66}},
}
